# Ändra localhost:4000 till er grupps basurl som ni fått.
@baseUrl=https://jau21-grupp1-mn2l2rop49wl.sprinto.se

# Hämtar alla recept
GET {{baseUrl}}/recipes HTTP/1.1

###

# Lägger till ett nytt recept
POST {{baseUrl}}/recipes HTTP/1.1
Content-Type: application/json

{
    "title": "Pennegroni",
    "description": "Pennegroni är en populär och trendig drink från baren Stranger i Göteborg. Den skapades 2019 av Josefine Thoren och är en blandning mellan de två drinkarna Negroni och Pendennis. Smakmässigt har drinken en balanserad blandning av sötma, syra, fruktighet och lite beska.",
    "ratings": [],
    "imageUrl": "https://drinkoteket.se/wp-content/uploads/pennegroni-860x860.jpg",
    "timeInMins": 5,
    "categories": [ "Gindrinkar"],
    "instructions": ["1. Häll alla ingredienser i en shaker.",
"2. Fyll shakern med is och skaka drinken kall.",
"3. Sila upp i ett isfyllt glas.",
"4. Garnera med en apelsinzest."],
    "ingredients": [
        {
            "name": "Gin",
            "amount": 2,
            "unit": "cl"
        },
        {
            "name": "Apricot Brandy",
            "amount": 2,
            "unit": "cl"
        },
        {
            "name": "Galliano",
            "amount": 1,
            "unit": "cl"
        },
        {
            "name": "Söt Vermouth (Röd)",
            "amount": 1,
            "unit": "cl"
        },
        {
            "name": "Citronjuice",
            "amount": 3,
            "unit": "cl"
        },
        {
            "name": "Agavesirap",
            "amount": 0.5,
            "unit": "cl"
        }
        
    ]
}

###

# Lägger till ett nytt recept
POST {{baseUrl}}/recipes HTTP/1.1
Content-Type: application/json

{
    "title": "Bruscetta",
    "description": "Att börja med",
    "ratings": [2, 3, 4, 1, 2, 3],
    "imageUrl": "https://assets.icanet.se/e_sharpen:80,q_auto,dpr_1.25,w_718,h_718,c_lfill/imagevaultfiles/id_223427/cf_259/korvstroganoff_med_ris.jpg",
    "timeInMins": 15,
    "categories": [ "Förrätt", "Italienskt" ],
    "instructions": [ "Stek brödet", "Hacka tomater och Mozarella", "Lägg på brödet"],
    "ingredients": [
        {
            "name": "Bröd",
            "amount": 1,
            "unit": "skiva"
        },
        {
            "name": "Tomat",
            "amount": 2,
            "unit": "stycken"
        }
    ]
}

###
# Söker bland alla recept
GET {{baseUrl}}/recipes?query=toas HTTP/1.1

###

# Hämtar ett enskilt recept
GET {{baseUrl}}/recipes/633d7a7f91dc8ff8a20d00cc HTTP/1.1

###

# Tar bort ett recept
DELETE {{baseUrl}}/recipes/632d9fcb6e7766b37d9837f5 HTTP/1.1

###

# Uppdaterar ett recept
PATCH {{baseUrl}}/recipes/632d9fcb6e7766b37d9837f5 HTTP/1.1
Content-Type: application/json

{
  "description": "Gott till apelsinsaft"
}

###

# Hämtar alla kategorier
GET {{baseUrl}}/categories HTTP/1.1

###

# Hämtar alla recept i en viss kategori (Förrätt)
GET {{baseUrl}}/categories/Vodkadrinkar/recipes HTTP/1.1

###

# Söker bland recept i en viss kategori
GET {{baseUrl}}/categories/Förrätt/recipes?query=brus HTTP/1.1

###

# Lägger till ett omdöme (1-5) för ett recept
POST {{baseUrl}}/recipes/632da30c6e7766b37d983811/ratings
Content-Type: application/json

{
    "rating": 1
}
###

# Hämtar alla kommentarer för ett recept
GET {{baseUrl}}/recipes/6330a9fee23753eb7d0ed415/comments

###

# Lägger till en kommentar för ett recept
POST {{baseUrl}}/recipes/6330a9fee23753eb7d0ed415/comments
Content-Type: application/json

{
    "comment": "För mycket salt!",
    "name": "Bosse"
}

###

# Tömmer all data i api:et
GET {{baseUrl}}/clear HTTP/1.1

###
